spring.application.name=x6.order
server.port=8083
springdoc.swagger-ui.path=/swagger-ui

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/x6_order
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD:admin}

spring.rabbitmq.addresses=localhost:5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=${RABBITMQ_PWD:guest}
spring.rabbitmq.virtual-host=x6_virtual_host

app.rabbitmq.queue=x6_queue
app.rabbitmq.exchange=x6_exchange

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml